import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import {Toaster} from "@/components/ui/toaster";
import Header from "@/components/header";
import getBeatsByUserId from "@/actions/getBeatsByUserId";
import Player from "@/components/player";

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const userBeats = await getBeatsByUserId();


  return (
    <html lang="en">
      <body className={font.className}>
      <SupabaseProvider>
        <UserProvider>
          <ModalProvider />

          <div className="flex flex-col h-full">
            <Header />
            <div className="flex-1 p-2">
              {children}
            </div>
          </div>

          <Player />
          <Toaster />
        </UserProvider>
      </SupabaseProvider>
      </body>
    </html>
  )
}
